# Generated by Django 3.2.8 on 2021-10-20 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('author', models.CharField(max_length=300)),
                ('publisher', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('book_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='stock', serialize=False, to='myapp.book')),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_data', models.FloatField()),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('book_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='myapp.book')),
            ],
        ),
    ]
